用于测试tensorflow的二维卷积运算

In [1]:
import tensorflow as tf
#case 2
input = tf.Variable(tf.random_normal([1,3,3,5]))
filter = tf.Variable(tf.random_normal([1,1,5,1]))

op2 = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='VALID')
#case 3
input = tf.Variable(tf.random_normal([1,3,3,5]))
filter = tf.Variable(tf.random_normal([3,3,5,1]))

op3 = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='VALID')
#case 4
input = tf.Variable(tf.random_normal([1,5,5,5]))
filter = tf.Variable(tf.random_normal([3,3,5,1]))

op4 = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='VALID')
#case 5
input = tf.Variable(tf.random_normal([1,5,5,5]))
filter = tf.Variable(tf.random_normal([3,3,5,1]))

op5 = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='SAME')
#case 6
input = tf.Variable(tf.random_normal([1,5,5,5]))
filter = tf.Variable(tf.random_normal([3,3,5,7]))

op6 = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='SAME')
#case 7
input = tf.Variable(tf.random_normal([1,5,5,5]))
filter = tf.Variable(tf.random_normal([3,3,5,7]))

op7 = tf.nn.conv2d(input, filter, strides=[1, 2, 2, 1], padding='SAME')
#case 8
input = tf.Variable(tf.random_normal([10,5,5,5]))
filter = tf.Variable(tf.random_normal([3,3,5,7]))

op8 = tf.nn.conv2d(input, filter, strides=[1, 2, 2, 1], padding='SAME')

init = tf.initialize_all_variables()
with tf.Session() as sess:
    sess.run(init)
    print("case 2")
    print(sess.run(op2))
    print("case 3")
    print(sess.run(op3))
    print("case 4")
    print(sess.run(op4))
    print("case 5")
    print(sess.run(op5))
    print("case 6")
    print(sess.run(op6))
    print("case 7")
    print(sess.run(op7))
    print("case 8")
    print(sess.run(op8))

W0919 11:28:28.133007 140085707626304 deprecation.py:323] From /home/tuzhuo/app/anaconda3/envs/jupyter/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py:193: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.


case 2
[[[[ 4.8107085 ]
   [-1.3151565 ]
   [ 2.8487983 ]]

  [[ 1.287185  ]
   [-0.9144621 ]
   [-0.79274756]]

  [[-6.319927  ]
   [ 3.047113  ]
   [ 2.4025311 ]]]]
case 3
[[[[-6.1892347]]]]
case 4
[[[[ 0.5603373]
   [ 6.5692463]
   [ 3.760872 ]]

  [[ 6.158585 ]
   [ 7.8717837]
   [ 7.538406 ]]

  [[ 7.605669 ]
   [ 8.806288 ]
   [12.311848 ]]]]
case 5
[[[[-2.3423903e+00]
   [ 1.2162489e+01]
   [ 4.8838496e+00]
   [ 7.6442480e+00]
   [ 1.7179636e+00]]

  [[ 1.4432720e+00]
   [-5.6034756e-01]
   [ 1.4835006e-01]
   [ 1.1469790e+00]
   [-3.3947244e+00]]

  [[-1.2599826e-02]
   [ 1.4968541e+00]
   [ 3.0761623e+00]
   [ 1.6130074e+00]
   [-1.2234118e+01]]

  [[-4.2228999e+00]
   [ 3.3235612e+00]
   [ 5.2604051e+00]
   [ 1.2987455e+01]
   [ 8.6747608e+00]]

  [[-8.5877562e+00]
   [-1.1069695e+01]
   [ 6.5071502e+00]
   [-9.5933151e+00]
   [-2.9958360e+00]]]]
case 6
[[[[-4.07716227e+00  3.03144574e+00  1.56954670e+00 -3.97479582e+00
     6.57551861e+00 -1.91728115e-01 -3.08002138e+00]
   